// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: internal/egress/egresspb/egress.proto

package egresspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EgressInfoRequest struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion             uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MinSupportedProtocolVersion uint32                 `protobuf:"varint,2,opt,name=min_supported_protocol_version,json=minSupportedProtocolVersion,proto3" json:"min_supported_protocol_version,omitempty"`
	Capabilities                []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *EgressInfoRequest) Reset() {
	*x = EgressInfoRequest{}
	mi := &file_internal_egress_egresspb_egress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressInfoRequest) ProtoMessage() {}

func (x *EgressInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_egress_egresspb_egress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressInfoRequest.ProtoReflect.Descriptor instead.
func (*EgressInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_egress_egresspb_egress_proto_rawDescGZIP(), []int{0}
}

func (x *EgressInfoRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *EgressInfoRequest) GetMinSupportedProtocolVersion() uint32 {
	if x != nil {
		return x.MinSupportedProtocolVersion
	}
	return 0
}

func (x *EgressInfoRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type EgressInfoResponse struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion             uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MinSupportedProtocolVersion uint32                 `protobuf:"varint,2,opt,name=min_supported_protocol_version,json=minSupportedProtocolVersion,proto3" json:"min_supported_protocol_version,omitempty"`
	Capabilities                []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Implementation              string                 `protobuf:"bytes,4,opt,name=implementation,proto3" json:"implementation,omitempty"`
	InstanceId                  string                 `protobuf:"bytes,5,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Error                       string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *EgressInfoResponse) Reset() {
	*x = EgressInfoResponse{}
	mi := &file_internal_egress_egresspb_egress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressInfoResponse) ProtoMessage() {}

func (x *EgressInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_egress_egresspb_egress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressInfoResponse.ProtoReflect.Descriptor instead.
func (*EgressInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_egress_egresspb_egress_proto_rawDescGZIP(), []int{1}
}

func (x *EgressInfoResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *EgressInfoResponse) GetMinSupportedProtocolVersion() uint32 {
	if x != nil {
		return x.MinSupportedProtocolVersion
	}
	return 0
}

func (x *EgressInfoResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *EgressInfoResponse) GetImplementation() string {
	if x != nil {
		return x.Implementation
	}
	return ""
}

func (x *EgressInfoResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *EgressInfoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type OutboxClientAckRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OutboxId        int64                  `protobuf:"varint,1,opt,name=outbox_id,json=outboxId,proto3" json:"outbox_id,omitempty"`
	TargetUserId    int64                  `protobuf:"varint,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	Pts             int32                  `protobuf:"varint,3,opt,name=pts,proto3" json:"pts,omitempty"`
	Attempt         int32                  `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	AuthKeyId       []byte                 `protobuf:"bytes,5,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	SessionId       int64                  `protobuf:"varint,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ServerMsgId     int64                  `protobuf:"varint,7,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	AckedAtUnixNano int64                  `protobuf:"varint,8,opt,name=acked_at_unix_nano,json=ackedAtUnixNano,proto3" json:"acked_at_unix_nano,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OutboxClientAckRequest) Reset() {
	*x = OutboxClientAckRequest{}
	mi := &file_internal_egress_egresspb_egress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboxClientAckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboxClientAckRequest) ProtoMessage() {}

func (x *OutboxClientAckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_egress_egresspb_egress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboxClientAckRequest.ProtoReflect.Descriptor instead.
func (*OutboxClientAckRequest) Descriptor() ([]byte, []int) {
	return file_internal_egress_egresspb_egress_proto_rawDescGZIP(), []int{2}
}

func (x *OutboxClientAckRequest) GetOutboxId() int64 {
	if x != nil {
		return x.OutboxId
	}
	return 0
}

func (x *OutboxClientAckRequest) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

func (x *OutboxClientAckRequest) GetPts() int32 {
	if x != nil {
		return x.Pts
	}
	return 0
}

func (x *OutboxClientAckRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *OutboxClientAckRequest) GetAuthKeyId() []byte {
	if x != nil {
		return x.AuthKeyId
	}
	return nil
}

func (x *OutboxClientAckRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *OutboxClientAckRequest) GetServerMsgId() int64 {
	if x != nil {
		return x.ServerMsgId
	}
	return 0
}

func (x *OutboxClientAckRequest) GetAckedAtUnixNano() int64 {
	if x != nil {
		return x.AckedAtUnixNano
	}
	return 0
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_internal_egress_egresspb_egress_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_egress_egresspb_egress_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_internal_egress_egresspb_egress_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_egress_egresspb_egress_proto protoreflect.FileDescriptor

const file_internal_egress_egresspb_egress_proto_rawDesc = "" +
	"\n" +
	"%internal/egress/egresspb/egress.proto\x12\x11telesrv.egress.v1\"\xa7\x01\n" +
	"\x11EgressInfoRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12C\n" +
	"\x1emin_supported_protocol_version\x18\x02 \x01(\rR\x1bminSupportedProtocolVersion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"\x87\x02\n" +
	"\x12EgressInfoResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12C\n" +
	"\x1emin_supported_protocol_version\x18\x02 \x01(\rR\x1bminSupportedProtocolVersion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12&\n" +
	"\x0eimplementation\x18\x04 \x01(\tR\x0eimplementation\x12\x1f\n" +
	"\vinstance_id\x18\x05 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\x97\x02\n" +
	"\x16OutboxClientAckRequest\x12\x1b\n" +
	"\toutbox_id\x18\x01 \x01(\x03R\boutboxId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\x03R\ftargetUserId\x12\x10\n" +
	"\x03pts\x18\x03 \x01(\x05R\x03pts\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\x05R\aattempt\x12\x1e\n" +
	"\vauth_key_id\x18\x05 \x01(\fR\tauthKeyId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\x03R\tsessionId\x12\"\n" +
	"\rserver_msg_id\x18\a \x01(\x03R\vserverMsgId\x12+\n" +
	"\x12acked_at_unix_nano\x18\b \x01(\x03R\x0fackedAtUnixNano\"%\n" +
	"\rErrorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\xcc\x01\n" +
	"\x10EgressAckService\x12V\n" +
	"\aGetInfo\x12$.telesrv.egress.v1.EgressInfoRequest\x1a%.telesrv.egress.v1.EgressInfoResponse\x12`\n" +
	"\x11AckOutboxDelivery\x12).telesrv.egress.v1.OutboxClientAckRequest\x1a .telesrv.egress.v1.ErrorResponseB+Z)telesrv/internal/egress/egresspb;egresspbb\x06proto3"

var (
	file_internal_egress_egresspb_egress_proto_rawDescOnce sync.Once
	file_internal_egress_egresspb_egress_proto_rawDescData []byte
)

func file_internal_egress_egresspb_egress_proto_rawDescGZIP() []byte {
	file_internal_egress_egresspb_egress_proto_rawDescOnce.Do(func() {
		file_internal_egress_egresspb_egress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_egress_egresspb_egress_proto_rawDesc), len(file_internal_egress_egresspb_egress_proto_rawDesc)))
	})
	return file_internal_egress_egresspb_egress_proto_rawDescData
}

var file_internal_egress_egresspb_egress_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_egress_egresspb_egress_proto_goTypes = []any{
	(*EgressInfoRequest)(nil),      // 0: telesrv.egress.v1.EgressInfoRequest
	(*EgressInfoResponse)(nil),     // 1: telesrv.egress.v1.EgressInfoResponse
	(*OutboxClientAckRequest)(nil), // 2: telesrv.egress.v1.OutboxClientAckRequest
	(*ErrorResponse)(nil),          // 3: telesrv.egress.v1.ErrorResponse
}
var file_internal_egress_egresspb_egress_proto_depIdxs = []int32{
	0, // 0: telesrv.egress.v1.EgressAckService.GetInfo:input_type -> telesrv.egress.v1.EgressInfoRequest
	2, // 1: telesrv.egress.v1.EgressAckService.AckOutboxDelivery:input_type -> telesrv.egress.v1.OutboxClientAckRequest
	1, // 2: telesrv.egress.v1.EgressAckService.GetInfo:output_type -> telesrv.egress.v1.EgressInfoResponse
	3, // 3: telesrv.egress.v1.EgressAckService.AckOutboxDelivery:output_type -> telesrv.egress.v1.ErrorResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_egress_egresspb_egress_proto_init() }
func file_internal_egress_egresspb_egress_proto_init() {
	if File_internal_egress_egresspb_egress_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_egress_egresspb_egress_proto_rawDesc), len(file_internal_egress_egresspb_egress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_egress_egresspb_egress_proto_goTypes,
		DependencyIndexes: file_internal_egress_egresspb_egress_proto_depIdxs,
		MessageInfos:      file_internal_egress_egresspb_egress_proto_msgTypes,
	}.Build()
	File_internal_egress_egresspb_egress_proto = out.File
	file_internal_egress_egresspb_egress_proto_goTypes = nil
	file_internal_egress_egresspb_egress_proto_depIdxs = nil
}
