// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: internal/egress/egresspb/egress.proto

package egresspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EgressAckService_GetInfo_FullMethodName           = "/telesrv.egress.v1.EgressAckService/GetInfo"
	EgressAckService_AckOutboxDelivery_FullMethodName = "/telesrv.egress.v1.EgressAckService/AckOutboxDelivery"
)

// EgressAckServiceClient is the client API for EgressAckService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EgressAckServiceClient interface {
	GetInfo(ctx context.Context, in *EgressInfoRequest, opts ...grpc.CallOption) (*EgressInfoResponse, error)
	AckOutboxDelivery(ctx context.Context, in *OutboxClientAckRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
}

type egressAckServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEgressAckServiceClient(cc grpc.ClientConnInterface) EgressAckServiceClient {
	return &egressAckServiceClient{cc}
}

func (c *egressAckServiceClient) GetInfo(ctx context.Context, in *EgressInfoRequest, opts ...grpc.CallOption) (*EgressInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EgressInfoResponse)
	err := c.cc.Invoke(ctx, EgressAckService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressAckServiceClient) AckOutboxDelivery(ctx context.Context, in *OutboxClientAckRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, EgressAckService_AckOutboxDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EgressAckServiceServer is the server API for EgressAckService service.
// All implementations must embed UnimplementedEgressAckServiceServer
// for forward compatibility.
type EgressAckServiceServer interface {
	GetInfo(context.Context, *EgressInfoRequest) (*EgressInfoResponse, error)
	AckOutboxDelivery(context.Context, *OutboxClientAckRequest) (*ErrorResponse, error)
	mustEmbedUnimplementedEgressAckServiceServer()
}

// UnimplementedEgressAckServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEgressAckServiceServer struct{}

func (UnimplementedEgressAckServiceServer) GetInfo(context.Context, *EgressInfoRequest) (*EgressInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedEgressAckServiceServer) AckOutboxDelivery(context.Context, *OutboxClientAckRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AckOutboxDelivery not implemented")
}
func (UnimplementedEgressAckServiceServer) mustEmbedUnimplementedEgressAckServiceServer() {}
func (UnimplementedEgressAckServiceServer) testEmbeddedByValue()                          {}

// UnsafeEgressAckServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EgressAckServiceServer will
// result in compilation errors.
type UnsafeEgressAckServiceServer interface {
	mustEmbedUnimplementedEgressAckServiceServer()
}

func RegisterEgressAckServiceServer(s grpc.ServiceRegistrar, srv EgressAckServiceServer) {
	// If the following call pancis, it indicates UnimplementedEgressAckServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EgressAckService_ServiceDesc, srv)
}

func _EgressAckService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EgressInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressAckServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressAckService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressAckServiceServer).GetInfo(ctx, req.(*EgressInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgressAckService_AckOutboxDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutboxClientAckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressAckServiceServer).AckOutboxDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressAckService_AckOutboxDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressAckServiceServer).AckOutboxDelivery(ctx, req.(*OutboxClientAckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EgressAckService_ServiceDesc is the grpc.ServiceDesc for EgressAckService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EgressAckService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telesrv.egress.v1.EgressAckService",
	HandlerType: (*EgressAckServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _EgressAckService_GetInfo_Handler,
		},
		{
			MethodName: "AckOutboxDelivery",
			Handler:    _EgressAckService_AckOutboxDelivery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/egress/egresspb/egress.proto",
}
